### ISSUE TITLE
PVH support in XEN PVM

### ISSUE THREAD

**Issue by jasenhn** [ganeti/ganeti#1265]
Hello,

As Xen 4.8 PVH support should be considered as "stabilised", as per https://blog.xenproject.org/2016/12/07/whats-new-with-xen-project-hypervisor-4-8/

Debian 9 ships with XEN 4.8, so having PVH-support in Ganeti as well would be a nice option.

This should be easy task, only "PVH=1" needs to be configured for a virtual machines xen config.

Enabling the PVH-feature could be like this:

gnt-instance modify -H pvh=true instance-name

Would any of the developers, please, have time for such a change?

**Comment by maznu** [comment]
+1 to this, especially given PVH is a mitigation for some of the problems in the Meltdown Attack. See: http://xenbits.xen.org/xsa/advisory-254.html

**Comment by flumeware** [comment]
I have made a patch for ganeti 2.15 which adds an option to include pvh support in the config file. The patches are incredibly rough and ready

Posted as gist here:
https://gist.github.com/flumeware/7bfa3e270712ba5bac4ccdaa815c092c

**Comment by fudcompliance** [comment]
+1 would be nice to have it in ganeti 2.16.1 . thanks

**Comment by rbott** [comment]
I will close this for now as there has not been on the en backends. We can always reconsider if people are actually using xen-pvm/hvm and need this.

**Comment by fussinator** [comment]
I'm using PVHv2.  It triples my multicast network speed, especially on old Xeons with Spectre/Meltdown issues.  I've also been using it on my non-Ganeti NFS server cluster for 5 years, with similar speed improvements.  Yes, Dom0 support for PVH (add via Xen kernel options with 'dom0=pvh') is experimental and doesn't seem to work yet.  But DomU support for PVH has been stable for years, and Ganeti doesn't manage Dom0 anyway.

Please reopen this request; many of us have been patiently waiting for it.  Right now I'm manually destroying domU with xl, and re-creating the domain before Ganeti does and adding 'type="pvh"' on the end of the 'xl create' command line.  This, of course, defeats the purpose of Ganeti.

For more background, PVH is PV with a hybridized, hardware-assisted-kick-in-the-pants for some slower privileged instructions and page tables (see https://wiki.xenproject.org/wiki/Understanding_the_Virtualization_Spectrum#The_Paravirtualization_Spectrum).

As I recall, the original Ganeti patch submission made a small change to the domain config template.  The line that should be added to the domU config is now 'type="pvh" '.  It can alternatively be added to the end of an xl command as 'type="pvh"'.

If you want to be thorough, 'type="pv"' will explicitly make a standard PV DomU, and 'type="hvm"' will make a fully-virtualized Xen HVM domain like KVM.  Currently, Xen assumes type=pv if type was not specified in the domain's config file.

That's all that needs to be added.  It could be specified by adding a Xen equivalent setting of the kvm_extras or extra_config paramters; call it 'xen_extras' maybe.  Or it could be a Xen-specific hvparam called 'type'.  The Ganeti Hypervisor field could display as 'xen-pvh' instead of 'xen-pvm' if you want to be explicit.
