### ISSUE TITLE
ganeti 2.15.2: master_candidate job queue management

### ISSUE THREAD

**Issue by abezella** [ganeti/ganeti#1266]
during a recent masterfailover our new cluster master kept losing its `ganeti-luxid` process, dying with errors like "openFile: resource exhausted (Too many open files)"

while investigating, it was noticed that there were a lot of old "job-[[:digit:]]+" files, stretching back quite some time, in the new master's `/var/lib/ganeti/queue`.  after some time and a number of restarts, luxid eventually stabilized.  our guess is that `ganeti-cleaner`, once this node was a master and the cleaner could run, eventually knocked down the queue backlog to the point that luxid was able to startup and process the remainder.

looking around our clusters, i've found that the master_candidates do indeed have a tendency to accumulate huge numbers of jobs in `/var/lib/ganeti/queue`.  10s of thousands in some cases, in others even throwing "ls: Argument list too long" errors.

it was suggested that this problem is related to #1149.

possible workarounds are to regularly failover the master to the candidates to keep the job
directories clean, or run some scripts with cron job that regularly clean the queue.

**Comment by ge-fa** [comment]
Thanks for bringing this up! IMHO, `/var/lib/ganeti/queue'` should also be handled.

**Comment by apoikos** [comment]
We were also affected by this. These are all `OP_GROUP_VERIFY_DISKS` jobs and they're left there because of a race condition in the way jobs are replicated and the way the watcher tries to archive them.

Currently the watcher spawns a single `OP_GROUP_VERIFY_DISKS` job per node-group, which it archives as soon as it has finished (presumably to avoid polluting the job queue with internal jobs).

Unfortunately this strategy is prone to a race that potentially leaves stale job files on all master candidates. The race comes down to the fact that ArchiveJob is called before the job has finished replicating to all master candidates, as these are two isolated threads of execution:

 1. The replication is triggered by the job code itself (via `UpdateJobUnlocked`) after each write. The job code runs on a dedicated process.

 2. Watcher waits for LuxiD to signal the job's completion, and LuxiD does so by watching the job file on the master using inotify. There is no locking involved and LuxiD will signal job completion as soon     as the file has been updated on the master, even though the updated file has not hit all master candidates yet.

There are a number of approaches to solving this issue, including:
 - Marking these ephemeral jobs as non-replicatable. While there is a provision to skip replicating jobs, it is not exposed to upper layers (e.g. via an argument to `SubmitJob`).

 - Introduce job-level locking between LuxiD and the job code. This is probably too complicated and does not seem to be needed anywhere else.

We opted for the quick-n-dirty solution of refactoring the watcher code to cleanup `OP_VERIFY_GROUP_DISKS` jobs on the next watcher run. This is done by marking jobs as "bulk" using the reason trail and querying the queue for such jobs after they have finished. While this approach does not eliminate the race, it certainly reduces the window so that we don't expect any duplicate job files to emerge in real world scenarios.

See https://github.com/apoikos/ganeti/commit/c9b839e1bfbc3d1c8b5a777e9d4e05b482db6294 for the fix.

**Comment by apoikos** [comment]
After thinking about this a bit, I think a good approach is to only archive jobs after the respective process is dead. I'll try to work on a patch for this.
