### ISSUE TITLE
GHC 8.2 compatibility

### ISSUE THREAD

**Issue by iustin** [ganeti/ganeti#1287]
I know that the 8.0 patch is not yet merged, but for fun (and because I only have this version), I tried compiling against 8.2.

It is almost possible, there are only two places where things have changes:

- Cabal (2.0 branch, the library) has changed how package build info is used, more precisely the macros are now per-target, not global, so this requires selecting the main lib target; see as example ekmett/distributive#17
- cabal-install (2.0 branch, the binary) defaults to sandboxes, which doesn't work with plain ghc invocations as the ganeti build does, so one must be careful to run `cabal --ignore-sandbox install …`
- Template Haskell again has changes, although trivial - DataD is trivially changed, but will require CPP-ing against the library version; for the context, see https://ghc.haskell.org/trac/ghc/wiki/Migration/8.2#template-haskell-2.12.0.0

I have a patch that makes 2.16 compile, and I didn't see the TH changes on master, so opening this for tracking. I have issues in the link stage though, so not yet ready for a pull request.

**Comment by apoikos** [comment]
8.2 is now in Debian unstable, and at least the Cabal changes prevent ganeti from building. @iustin, could you share the patch :slightly_smiling_face: ?

**Comment by apoikos** [comment]
I managed to get the Debian package to build with GHC 8.2.2.

The TH patch that I applied on top of our previous TH patches for 8.0 can be found here: https://salsa.debian.org/ganeti-team/ganeti/blob/master/debian/patches/THH-2.12.patch

For Cabal, I tweaked the code to generate macros only for the main lib, as @iustin suggested, since all other components essentially depend on nothing but the lib itself. Patch here: https://salsa.debian.org/ganeti-team/ganeti/blob/master/debian/patches/cabal-2.0.patch

**Comment by apoikos** [comment]
Closed via b160a9eb42d5b3e70a680f2bed805b4c1c06719c and ceccc4e2e7a6edd42555cde399a7df382b8f5f66.
