### ISSUE TITLE
Determine targeted Python 3 versions

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1366]
We need to determine the minimum supported version of Python 3 to work on. Unlike Python 2 which has effectively been frozen with the release of 2.7 in 2010, Python 3 is still changing and things like `asyncio` (which replaces `asyncore`) or the type decorators have appeared quite recently.

Distribution | Version 
---------------|----------
Debian Stretch | 3.5.3
Debian Buster | 3.7.2
Ubuntu 18.04 LTS | 3.6.5
Ubuntu 16.04 LTS | 3.5.1
CentOS/RHEL 7 | - (3.6 via [software collections](https://www.softwarecollections.org/en/), 3.5 via [RedHat Software Collections](https://access.redhat.com/products/Red_Hat_Enterprise_Linux/Developer/#rhscl=&dev-page=5))

It seems 3.5 would give us the best in terms of compatibility with existing distributions, however 3.6 introduced a number of significant improvements that Ganeti can benefit from, most importantly:
 - PEP 526, syntax for variable annotations
 - Stable `asyncio` API, replacing `asyncore`

None of these is essential, but both would be nice to have, so the question is whether it's worth breaking compatibility with Debian Stretch and Ubuntu Xenial. I'm leaning towards a "no" here.

**Comment by iustin** [comment]
Hmm, I'd be inclined to say only support 3.7. If 18.04 LTS would have it, I'd be strongly for it.

It really depends on what the version that switches to 3 is supposed to be. If it's a normal release (i.e. with new features), then making it available on as many platforms as possible is a must. However, I see a migration to Python 3 being more a standalone thing, and not bundled with significant other things, in which case whether you move to it or not should be a free choice, not required.

As to 3.5, it only enables Stretch. And Stretch has a good 2.16 via backports, and will have 2.16.1, and on top Buster will be here much earlier than a next release of Ganeti. I don't see why Stretch would _need_ to have the Python3-enabled version of Ganeti.

OTOH, 3.7 does have quite a bit of improvements over 3.6, e.g. even asyncio [is better](https://docs.python.org/3.7/whatsnew/3.7.html#asyncio). But 3.7 is only available to day in Buster, so that's too new.

Therefore, i'd say aim for 3.6.

**Comment by jfut** [comment]
Python 3.6 is good! [In RHEL 8, Python 3.6 is the default](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/), fully supported version of Python.

| Distribution | Version |
----------------| -------|
| RHEL 8.0 Beta | 3.6.6  |

**Comment by YSelfTool** [comment]
I have a branch at https://github.com/YSelfTool/ganeti/tree/python3 with which the python unit-tests (`make py-tests`) succeed with python3. That does not mean the python3-support is done, since e.g. the import-export daemon (`test/py/import-export_unittest.bash`) still does not work with python3, that unittest is just not included in `make py-tests`. It is also rather painful to port due to all the indirection in it.
I've also not tried anything with a real cluster, just unittests so far.
But it should still be a good step towards python3 support.

**Comment by apoikos** [comment]
@YSelfTool: looks like we have some overlap :) I've done pretty-much the same work at https://github.com/apoikos/ganeti/commits/python3-next, working on Python 3.7. I think we should try to merge our efforts, what do you think?

**Comment by apoikos** [comment]
@YSelfTool: btw, nice work! Will you be attending GanetiCon?

**Comment by apoikos** [comment]
During the conversion done in #1404, the minimum required version was set to 3.6. I think this can be closed for now.
