### ISSUE TITLE
Stop using QEMU's human monitor

### ISSUE THREAD

**Issue by apoikos** [ganeti/ganeti#1542]
Right now we are using a mix of HMP and QMP calls to QEMU, depending on the feature. This adds complexity to the code and confusion to contributors over picking which method to use. Since QMP is supposed to be the machine interface of QEMU, it makes sense to switch everything over to it.

We currently use the human monitor for the following operations:

 - To get CPU thread information (`info cpus`, QMP command: `query-cpus`, since 0.14)
 - To set the VNC password (`change vnc password`, QMP command: `change` with arguments, since 0.14)
 - To hot-add drives (`drive_add`, QMP command: `blockdev-add`, since 2.9)
 - To hot-remove drives (`drive_del`, QMP command: `blockdev-del`, since 2.9)
 - To signal shutdown to the guest (`system_powerdown`, QMP command: `system_powerdown`, since 0.14)
 - To balloon the guest memory (`balloon`, QMP command: `balloon`, since 0.14)
 - To get version information (`info version`, QMP command: `query-version`, since 0.14)

(The information on the QMP commands can be found under `qapi/` in the QEMU source)

Migrating all these calls to QMP bumps our compatibility to QEMU >= 2.9, which was released in 2017. Since we are anyway no longer compatible with Xenial and Stretch because of Python 3/GHC, there's nothing to lose here.

**Comment by rbott** [comment]
I entirely agree. I will try to tackle some of these, since I have already done some work on this end in the past month. I'll update this issue when I start working on any of the above tasks.

**Comment by rbott** [comment]
Parts if this PR have been addressed by #1546 (and bumped the minimum QEMU version to 2.12). However, there is still some work to do :-)

**Comment by rbott** [comment]
@saschalucas @apoikos there is now only the block device part left to address. However, this seems to a bit more complicated: according to [this slidedeck](http://events17.linuxfoundation.org/sites/events/files/slides/talk_11.pdf) `blockdev-add|del` in QMP do not directly correspond to `drive_del|add` in HMP and especially not to the `-drive` commandline parameter of QEMU.

The latter is deprecated and should be replaced by the `-blockdev` parameter (which in turn is in line with `blockdev-add`).

So I guess we need to entirely replace the `-drive/drive_add/drive_del` combination. AFAICT this also makes the `disk_cache` parameter obsolete as it does not exist any more in this context (other block device related parameters like `aio`, `discard` etc. are still available).

Replacing the entire code is one thing, taking care of migrating between `-drive` and `-blockdev` is probably going to take some more consideration.

I think this is a worthwhile feature for 3.1 but will probably also bump version requirements for QEMU quite a bit. `-blockdev` has been present since 2.9 but was apparently declared rather unstable in early versions. This change will require some extensive testing to see how well our use case works with older releases.

**Comment by apoikos** [comment]
@rbott QEMU 2.9 was ages ago, I think it's perfectly fine to restrict ourselves to QEMU >= 3 (or even 4).

**Comment by apoikos** [comment]
@rbott: digging a bit into QEMU history, QMP `blockdev-add` and `blockdev-del` have been _stable_ as of QEMU 2.9 (see qemu/qemu@79b7a77eda5118f2661d251820d5ee9ee080354a). `-blockdev` is using `qmp_blockdev_add` internally (see qemu/qemu@42e5f39378c6e7a0ada563779bbb6f470f7c03ff) and was also part of 2.9. In short, it looks like 2.9 is all we need for proper QMP blockdev support.

Changing the code should be straightforward once we decide to only use QMP, we just need to check if there's anything affecting running instances and live migrations.
