### ISSUE TITLE
disk hotplug broken with Ubuntu Focal / QEMU 4.2

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1547]
I recently enabled hotplug tests in the testsuite for my nightly QA runs and they [fail|https://salsa.debian.org/rbott/ganeti-build/-/jobs/1288613] on Ubuntu Focal.

```
Command: ssh gnt-test01 'gnt-instance modify --disk -1:add,size=1G --hotplug kvm-test-instance02'
Warning: Permanently added 'gnt-test01,192.168.122.11' (ECDSA) to the list of known hosts.
Stdout was:
Mon Dec 28 09:55:53 2020  - INFO: Trying to hotplug device...
Mon Dec 28 09:55:53 2020  - WARNING: Could not hotplug device: Error while executing backend function: kvm: error executing the device_add command: Property 'virtio-blk-device.drive' can't find value 'disk-e38c1b24-92f7-4f51' (GenericError):
Mon Dec 28 09:55:53 2020  - INFO: Continuing execution..
Mon Dec 28 09:55:53 2020  - INFO: Waiting for instance kvm-test-instance02 to sync disks
Mon Dec 28 09:55:53 2020  - INFO: - device disk/2:  3.20% done, 35s remaining (estimated)
Mon Dec 28 09:56:29 2020  - INFO: Instance kvm-test-instance02's disks are in sync
Modified instance kvm-test-instance02
 - disk/2 -> add:size=1024,mode=rw
 - disk/2 -> hotplug:failed
Please don't forget that most parameters take effect only at the next (re)start of the instance initiated by ganeti; restarting from within the instance will not be enough.
```

Hotplugging a NIC seems to be no problem. I have not yet investigated this any further. Just for the record: Focal runs QEMU 4.2.

**Comment by apoikos** [comment]
Disk hotplugging uses a "tricky" path, because it was written before the `blockdev-add` and `blockdev-del` QMP commands were properly implemented. It uses the human monitor to issue a `drive_add` command using an fd passed with `SCM_RIGHTS` over the monitor socket, and then it issues a `device_add` command through QMP. AFAICT, in this case `device_add` does not seem to find the drive that is supposed to have been created by `drive_add`. Unfortunately, the output of `drive_add` is discarded, so we don't know what happened there.

@rbott, can you patch locally and re-run using the following patch:
```diff
diff --git a/lib/hypervisor/hv_kvm/__init__.py b/lib/hypervisor/hv_kvm/__init__.py
index 9ba39c136..7a71f925e 100644
--- a/lib/hypervisor/hv_kvm/__init__.py
+++ b/lib/hypervisor/hv_kvm/__init__.py
@@ -2287,7 +2287,8 @@ class KVMHypervisor(hv_base.BaseHypervisor):
         """Helper function that uses HMP to hot-add a drive."""
         cmd = "drive_add dummy file=%s,if=none,id=%s,format=raw" % \
           (filename, kvm_devid)
-        self._CallMonitorCommand(instance.name, cmd)
+        res = self._CallMonitorCommand(instance.name, cmd)
+        logging.warning("drive_add returned: %s", res.stdout.read())
 
       # This must be done indirectly due to the fact that we pass the drive's
       # file descriptor via QMP first, then we add the corresponding drive that

```

**Comment by apoikos** [comment]
Debian bug [\#939413](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939413) seems to be relevant.

**Comment by apoikos** [comment]
So, QEMU 3.1 added the `auto-read-only` drive option, which in 4.0 was enabled by default for many drivers (including `file`) and was made "dynamic". What this means it that without explicit configuration (`auto_read_only=off`), all file-backed drives are opened in read-only mode and are upgraded once the first writer appears. In order for this to work with fdsets, we need two provide _two_ file descriptors: one in read-write mode, and one in read-only mode.

Note that we could disable the auto-read-only behavior, but it's there for a reason and to disable it we'd need to test the qemu version (again). On the other hand, passing two fds instead of one is backwards compatible and apart from the apparent waste of a file descriptor, should cause no other harm.
