### ISSUE TITLE
haskell tests fail with json-0.10

### ISSUE THREAD

**Issue by jfut** [ganeti/ganeti#1570]
Hi,

haskell tests fail with json-0.10.

Steps to reproduce:

- docker.pkg.github.com/ganeti/ci-images/focal:latest
- json-0.10

```
apt remove libghc-json-dev
cabal update
cabal install --only-dependencies cabal/ganeti.template.cabal
./autogen.sh
./configure --enable-haskell-tests
make -j 2 hs-tests
```

Error output:

```
         Properties    Test Cases    Total
 Passed  318           121           439
 Failed  9             6             15
 Total   327           127           454
```

Typical failure case:

```
Confd/Types:
  ConfdQuery_serialisation: [OK, passed 500 tests]
  ConfdQuery_BadTypes: [Failed]
ERROR: Cannot deserialise into ConfdQuery the value 'JSRational False (1 % 1)'
  ConfdReplyStatus_serialisation: [OK, passed 500 tests]
  ConfdReply_serialisation: [OK, passed 500 tests]
  ConfdErrorType_serialisation: [OK, passed 500 tests]
  ConfdNodeRole_serialisation: [OK, passed 500 tests]
```

- json-0.9.3 works fine

```
         Properties    Test Cases    Total
 Passed  327           127           454
 Failed  0             0             0
 Total   327           127           454
```

**Comment by saschalucas** [comment]
Thanks for your finding. @apoikos: I assume this affects [Debian Bullseye](https://packages.debian.org/search?suite=bullseye&searchon=names&keywords=libghc-json-dev), too (libghc-json-dev-0.10-1+b1)?

**Comment by apoikos** [comment]
@jfut thanks for the report! I'm a bit puzzled, because our [nightly builds on Debian testing](https://github.com/ganeti/ganeti/runs/1811897729?check_suite_focus=true) are successful, and from what I can see at the configure stage output it's testing against json-0.10. Also, json-0.10 has been [part of Debian testing since August](https://tracker.debian.org/pkg/haskell-json) and we haven't seen any failures.

I'm inclined to say this is a focal-specific issue when building json by hand through cabal, but I would like to confirm this.

**Comment by apoikos** [comment]
It turns out this is an incompatibility between GHC 8.6 and json-0.10, see https://github.com/GaloisInc/json/issues/12. json has been fixed, but the fix has not yet been released.

I'm closing this since there's nothing to be done on our side.

**Comment by jfut** [comment]
Thank you for checking!
