### ISSUE TITLE
xen: drop support for `xm` command

### ISSUE THREAD

**Issue by rbott** [ganeti/ganeti#1611]
Some years ago the Xen project  deprecated and finally dropped the `xm` command and replaced it with the `xl` command. Ganeti contains code for both commands and also defaults to using `xm`, leading to a bad user experience for users of the Xen hypervisor.

We should:
* drop all code/settings/tests related to `xm`
* remove the `xen_cmd` property
* remove all references to `xm` from the documentation

**Comment by atta** [comment]
We should have a vote and and have some kind request for people who like to
keep the code alive.

Rudolph Bott ***@***.***> schrieb am Sa., 2. Okt. 2021, 13:15:

**Comment by iustin** [comment]
Uh, sorry to ask, but why have a vote? As in, why keep the old code alive since it doesn't work well with recent Xen?

Given the lack of developer power in the project, I'd vote +1 to every proposal about simplifying the code base and removing seldom used features. The problem is that this codebase was "sized" (if I can express it like this) for a 3-4 permanent developers team, and we lack about 3-4 of those :(

**Comment by rbott** [comment]
I'd go with @iustin here. `xm` has been deprecated/removed around 2018 (from what I've found) so we are already some years behind. I don't think we need to have support for older Xen versions :-)
As the xen codebase is already quite untested, making it smaller will only help.
I am currently trying to setup Xen clusters as nested KVM guests on the setup where I already run KVM-in-KVM tests with the QA suite. Maybe we can get some more insights on the state of Xen in Ganeti soon.

**Comment by iustin** [comment]
Side-note: Many years ago, I was doing Xen testing as nested KVM guests, so this should work (I assume things only got better, not worse). Very useful as dedicated Xen hosts are costly :)
