### ISSUE TITLE
Makefile.ghc generation broken in Ubuntu Noble (24.04 / GHC-9.4)?

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1755]
As noted in #1748 there is a Type error exposed using `make` and not `Cabal`. With this workaround:

```diff
diff --git a/src/Ganeti/Lens.hs b/src/Ganeti/Lens.hs
index c6184ea..32fcc2f 100644
--- a/src/Ganeti/Lens.hs
+++ b/src/Ganeti/Lens.hs
@@ -93,14 +93,14 @@ makeCustomLenses' name lst = makeCustomLensesFiltered f name
 -- Most often the @g@ functor is @(,) r@ and 'traverseOf2' is used to
 -- traverse an effectful computation that also returns an additional output
 -- value.
-traverseOf2 :: Over (->) (Compose f g) s t a b
-            -> (a -> f (g b)) -> s -> f (g t)
+-- traverseOf2 :: Over (->) (Compose f g) s t a b
+--             -> (a -> f (g b)) -> s -> f (g t)
 traverseOf2 k f = getCompose . traverseOf k (Compose . f)
 
 -- | Traverses over a composition of a monad and a functor.
 -- See 'traverseOf2'.
-mapMOf2 :: Over (->) (Compose (WrappedMonad m) g) s t a b
-        -> (a -> m (g b)) -> s -> m (g t)
+-- mapMOf2 :: Over (->) (Compose (WrappedMonad m) g) s t a b
+--         -> (a -> m (g b)) -> s -> m (g t)
 mapMOf2 k f = unwrapMonad . traverseOf2 k (WrapMonad . f)
 
 -- | A helper lens over sets.
```
compilation goes further until:
```
[GHC]: src/mon-collector.o <- cabal_macros.h

src/mon-collector.hs:38:1: error:
    Could not find module ‘Ganeti.DataCollectors.CLI’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
38 | import Ganeti.DataCollectors.CLI (genericOptions, defaultOptions)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/mon-collector.hs:39:1: error:
    Could not find module ‘Ganeti.DataCollectors.Program’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
39 | import Ganeti.DataCollectors.Program (personalities)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
make: *** [Makefile:4361: src/mon-collector.o] Error 1
```

I'm not sure, but does this indicate a dependency problem caused by a wrong `Makefile.ghc`? Comparing `Makefile.ghc` between Ubuntu Noble and Jammy shows a big difference:
```bash
$ wc -l /tmp/Makefile.ghc-* 
  5837 /tmp/Makefile.ghc-jammy
  1993 /tmp/Makefile.ghc-noble
```

So I assume the way how `Makefile.ghc` is generated is broken with newer GHCs? https://github.com/ganeti/ganeti/blob/8a06656acf8f6e3dfa907bea77bd57a469a8d3fb/Makefile.am#L1349-L1364

@thielema can this explain the type error in #1748 using `make`?

It seems that a static Cabal file as proposed in #1747 and a switch to  `Cabal` build is a good idea.

**Comment by thielema** [comment]
On Thu, 18 Jul 2024, saschalucas wrote:

> I'm not sure, but does this indicate a dependency problem caused by a 
> wrong Makefile.ghc? Comparing Makefile.ghc between Ubuntu Noble and 
> Jammy shows a big difference:
> 
> $ wc -l /tmp/Makefile.ghc-*
>   5837 /tmp/Makefile.ghc-jammy
>   1993 /tmp/Makefile.ghc-noble

What are the differences in the generated ganeti.cabal's?


> So I assume the way how Makefile.ghc is generated is broken with newer GHCs?

That's how it looks like.

> @thielema can this explain the type error in #1748 using make?

Likely not, because that affects a module that is compiled after 
Ganeti.Lens.


> It seems that a static Cabal file as proposed in #1747 and a switch to 
> Cabal build is a good idea.

indeed

**Comment by saschalucas** [comment]
> What are the differences in the generated ganeti.cabal's?

There are no differences between the jammy's and noble's `ganeti.cabal`

**Comment by thielema** [comment]
With the commit https://github.com/thielema/ganeti/tree/patch-2 Ubuntu/Noble is happy with `Ganeti.Lens`. Unfortunately, the problem with incomplete `Makefile.ghc` persists.

**Comment by thielema** [comment]
On Thu, 18 Jul 2024, saschalucas wrote:

> There are no differences between the jammy's and noble's ganeti.cabal

I am afraid there is a bug introduced in GHC-9.4:

https://gitlab.haskell.org/ghc/ghc/-/issues/25113

**Comment by saschalucas** [comment]
On Fri, 26 Jul 2024, thielema wrote:

> I am afraid there is a bug introduced in GHC-9.4:
>
> https://gitlab.haskell.org/ghc/ghc/-/issues/25113

Thanks for filling this ghc issue. Let's see if this will be fixed by
upstream in GHC-9.4. If so, I think there are chances to get this into
Debian and maybe even into Ubuntu-24.04 ... but I suspect huge delays.

It might be worth to keep in mind switching away from Makefile.ghc to
Cabal build.

**Comment by thielema** [comment]
On Fri, 26 Jul 2024, saschalucas wrote:

> Thanks for filling this ghc issue. Let's see if this will be fixed by 
> upstream in GHC-9.4. If so, I think there are chances to get this into 
> Debian and maybe even into Ubuntu-24.04 ... but I suspect huge delays.

Latest version in the GHC-9.4 series is 9.4.8. That's one of the highest 
minor versions for GHC, at all. Thus I am afraid, GHC-9.4 is pretty much 
closed and they will not release another fix.

That said, how can we work around the bug? I see these alternatives:

1. Run `ghc -M` once for each executable and concatenate the resulting 
Makefiles. This means that some modules and their dependencies are 
mentioned more than once, but I think `make` tolerates this. Or we 
postprocess with `sort --unique`.

2. Make one Super-Main module that somehow imports all required modules 
and run `ghc -M` on this one.

2.1. One way would be to write a module that imports src/htools.hs, 
src/ganeti-kvmd.hs and so on. That's not actually so simple, because all 
executable main modules have the module name Main. We would have to rename 
them.

2.2. Collect the imports of the executables and put them together in one 
Super-Main module. That would require that grepping for 'import' only 
yields valid import statements.


Currently I think I go with the first alternative.


> It might be worth to keep in mind switching away from Makefile.ghc to 
> Cabal build.

It seems that Ganeti is the last project in the real world that uses this 
Makefile generation, otherwise the bug would have been reported earlier. 
It is present in all GHC versions from 9.4 to 9.10.

I would prefer to switch to Cabal build sooner than later, however, it 
encounters some other obstacles. So I'd go with quick fix for now.

**Comment by saschalucas** [comment]
Thanks @thielema for your opinion on fixing this in GHC-9.4. Chances seems pretty low.

Your suggested solution to run  `ghc -M` once for each executable seems the best way to quickly solve this issue.
